---
- include_tasks: linux-common.yml
  when: (ansible_os_family | lower == 'redhat') or (ansible_os_family | lower == 'debian')
  
- include_tasks: redhat.yml
  when: ansible_os_family | lower == 'redhat'

- include_tasks: debian.yml
  when: ansible_os_family | lower == 'debian'

- include_tasks: windows.yml
  when: ansible_os_family | lower == 'windows'
