---
# tasks file for RHEL7-CIS
- name: Check OS distro
  fail:
    msg: "OS is not Red Hat, failing"
  when: ansible_os_family != 'RedHat'

- name: Check OS version
  fail:
    msg: "RHEL version is not 7, failing"
  when: ansible_distribution_major_version is version_compare('7', '!=')

- name: Check ansible version
  fail:
    msg: You must use ansible 2.1 or greater
  when: ansible_version.full is not version_compare('2.1', '>=')

- include: prelim.yml
  become: yes
  tags:
      - prelim_tasks

- include: section1.yml
  become: yes
  when: rhel7cis_section1

- include: section2.yml
  become: yes
  when: rhel7cis_section2

- include: section3.yml
  become: yes
  when: rhel7cis_section3

- include: section4.yml
  become: yes
  when: rhel7cis_section4

- include: section5.yml
  become: yes
  when: rhel7cis_section5

- include: section6.yml
  become: yes
  when: rhel7cis_section6

# - include: post.yml
#   become: yes
#   tags:
#       - post_tasks
#       - always
