---

# Public IP workaround START
- name: Check for Public IP
  azure_rm_publicipaddress_facts:
    resource_group: "{{ resource_groups[0]['name'] }}"
    name: "{{ inventory_hostname }}_ip"
  delegate_to: localhost
  register: pub_ip
  when: (needs_public_ip is defined) and (needs_public_ip == True)

- name: Override ansible_host with public IP
  set_fact:
    ansible_host: "{{ pub_ip.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
  when: (needs_public_ip is defined) and (needs_public_ip == True)

- name: Obtain server facts
  setup:
# Public IP workaround END


- include_tasks: configure-dhclient.yml
  when: (ansible_os_family | lower == 'redhat') or (ansible_os_family | lower == 'debian')

- include_tasks: configure-fqdn.yml
  when: (ansible_os_family | lower == 'redhat') or (ansible_os_family | lower == 'debian')

- include_tasks: linux-common.yml
  when: (ansible_os_family | lower == 'redhat') or (ansible_os_family | lower == 'debian')

# Disabled until networking is in place to support traffic to/from K5 patch servers
# - include_tasks: configure-repo-apt.yml
#   when: ansible_os_family | lower == 'debian'

# - include_tasks: configure-repo-yum.yml
#   when: ansible_os_family | lower == 'redhat'
  
- include_tasks: redhat.yml
  when: ansible_os_family | lower == 'redhat'

- include_tasks: debian.yml
  when: ansible_os_family | lower == 'debian'

- include_tasks: windows.yml
  when: ansible_os_family | lower == 'windows'
