---
# Role tasks file

- name: Get subscription ID from credential
  set_fact:
    cred_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"

- name: Subscription ID check
  assert:
    msg: "Inventory id {{ subscription_id }} MUST match credential id {{ cred_subscription_id }}"
    that: (subscription_id == cred_subscription_id)  

- name: Create Resource Group
  azure_rm_resourcegroup:
    name: "{{ item.name }}"
    location: "{{ item.location }}"
  loop: "{{ resource_groups }}"

- name: Create Virtual Networks
  azure_rm_virtualnetwork:
    name: "{{ item.name }}"
    resource_group: "{{ item.resource_group }}"
    address_prefixes_cidr: "{{ item.ip_cidr }}"
  loop: "{{ virtual_networks }}"

- name: Create Subnets
  azure_rm_subnet:
    name: "{{ item.name }}"
    resource_group: "{{ item.resource_group }}"
    address_prefix_cidr: "{{ item.ip_cidr }}"
    virtual_network_name: "{{ item.vnet }}"
    security_group: "{{ security_groups_subnet | default('') }}"
  loop: "{{ subnets }}"

- name: Create Security Groups
  azure_rm_securitygroup:
    name: "{{ item.name }}"
    resource_group: "{{ item.resource_group }}"
    purge_rules: "{{ purge_existing | default('yes') }}"
    rules: "{{ item.rules }}"
  loop: "{{ security_groups }}"
