---
# Role tasks file

# Optional step

- name: debug public ip
  debug:
    var: needs_public_ip
  delegate_to: localhost

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ resource_groups[0]['name'] }}"
    allocation_method: Static
    name: "{{ inventory_hostname }}_ip"
  delegate_to: localhost
  when: (needs_public_ip is defined) and (needs_public_ip)

- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ resource_groups[0]['name'] }}"
    name: "{{ inventory_hostname }}_nic"
    virtual_network: "{{ virtual_networks[0]['name'] }}"
    subnet: "{{ subnets[0]['name'] }}"
    ip_configurations:
      - name: ipconfig1
        private_ip_address: "{{ ansible_host }}"
        public_ip_address_name: "{{ inventory_hostname }}_ip"
        primary: true
    security_group: "{{ sg | default('SSH') }}"
  delegate_to: localhost


# - name: Create VM
#   azure_rm_virtualmachine:
#     resource_group: "{{ resource_groups[0]['name'] }}"
#     name: "{{ inventory_hostname }}"
#     vm_size:
#     storage_account:
#     storage_container:
#     storage_blob:
#     admin_username:
#     admin_password:
#     network_interface:
#     image:
#       offer:
#       publisher:
#       sku:
#       version: latest
