---
# Role tasks file

- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ resource_groups[0]['name'] }}"
    name: "{{ inventory_hostname }}_nic"
    virtual_network: "{{ virtual_networks[0]['name'] }}"
    subnet: "{{ subnets[0]['name'] }}"
    ip_configurations:
      - name: ipconfig1
        public_ip_address_name: "{{ inventory_hostname }}_ip"
        primary: true
    security_group: "{{ sg | default('SSH') }}"
  delegate_to: localhost

# - name: Create VM
#   azure_rm_virtualmachine:
#     resource_group: "{{ resource_groups[0]['name'] }}"
#     name: "{{ inventory_hostname }}"
#     vm_size:
#     storage_account:
#     storage_container:
#     storage_blob:
#     admin_username:
#     admin_password:
#     network_interface:
#     image:
#       offer:
#       publisher:
#       sku:
#       version: latest
