---
# Role tasks file

# Optional step

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ resource_groups[0]['name'] }}"
    allocation_method: Static
    name: "{{ inventory_hostname }}_ip"
  delegate_to: localhost
  when: (needs_public_ip is defined) and (needs_public_ip == True)
  register: pub_ip

- debug: var=pub_ip

- meta: end_play

- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ resource_groups[0]['name'] }}"
    name: "{{ inventory_hostname }}_nic"
    virtual_network: "{{ virtual_networks[0]['name'] }}"
    subnet: "{{ subnets[0]['name'] }}"
    ip_configurations:
      - name: ipconfig1
        private_ip_address: "{{ ansible_host }}"
        public_ip_address_name: "{% if (needs_public_ip is defined) and (needs_public_ip == true) %}{{ inventory_hostname }}_ip{% else %}{{ omit }}{% endif %}"
        primary: true
    security_group: "{{ sg | default('SSH') }}"
  delegate_to: localhost


- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource_groups[0]['name'] }}"
    name: "{{ inventory_hostname }}"
    vm_size: "{{ vm_size }}"
    managed_disk_type: "{{ managed_disk_type }}"
    admin_username: "{{ admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
        key_data: "{{ public_key }}"
    network_interface_names: "{{ inventory_hostname }}_nic"
    image:
      offer: "{{ image.offer }}"
      publisher: "{{ image.publisher }}"
      sku: "{{ image.sku }}"
      version: "{{ image.version }}"
  delegate_to: localhost